version: '3.9'

services:
  db:
    container_name: postgres-skipulse
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
     - /home/spawn/Developer/docker_volumns/postgres/data:/var/lib/postgresql/data
